services:
  db:
    image: mysql:8.0
    container_name: db-container-sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password 
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports: 
      - "8080:8080"